import type { CallHistoryEntry } from "./types";

export const callHistory: CallHistoryEntry[] = [
  {
    id: "ch-1",
    caller: "Marcus Webb",
    fromNumber: "+1 (415) 555-0142",
    toNumber: "+1 (415) 555-0100",
    direction: "inbound",
    status: "completed",
    outcome: "follow_up_scheduled",
    roleIds: ["financial"],
    dateLabel: "Today",
    startedAtLabel: "09:12",
    durationSeconds: 754,
    twilioSid: "CA9f2b1c7d4e8a06b3f1d2c9a7e5b4c3d2",
    elevenConversationId: "elc_7f13ab90c2",
    recordingAvailable: true,
    model: "grok-2",
    toolCalls: 3,
    summary:
      "Reviewed Q3 positioning ahead of a board call; agreed to send a one-pager and reconnect Friday.",
    transcript: [
      {
        id: "ch1-u1",
        speaker: "caller",
        text: "Hi — I wanted to walk through Q3 positioning before the board call.",
        timestamp: "00:04",
      },
      {
        id: "ch1-u2",
        speaker: "twin",
        text: "Of course. The portfolio is up 2.1% quarter-to-date, mostly from the technology overweight.",
        timestamp: "00:12",
      },
      {
        id: "ch1-u3",
        speaker: "whisper",
        text: "Mention Thursday's Fed meeting and the duration view.",
        timestamp: "00:19",
        whisperStatus: "spoken",
      },
      {
        id: "ch1-u4",
        speaker: "twin",
        text: "With the Fed meeting Thursday, we have kept duration slightly short as a hedge against a hawkish surprise.",
        timestamp: "00:25",
      },
      {
        id: "ch1-u5",
        speaker: "caller",
        text: "Good. Can you send me the one-pager and put time on Friday?",
        timestamp: "00:41",
      },
      {
        id: "ch1-u6",
        speaker: "twin",
        text: "Done — the one-pager is queued and I have sent a hold for Friday at 10.",
        timestamp: "00:48",
      },
    ],
    whispers: [
      {
        id: "ch1-w1",
        text: "Mention Thursday's Fed meeting and the duration view.",
        queuedAt: "00:19",
        spokenAt: "00:25",
        usedInTraining: true,
      },
    ],
  },
  {
    id: "ch-2",
    caller: "Sarah Lin",
    fromNumber: "+1 (415) 555-0100",
    toNumber: "+1 (206) 555-0188",
    direction: "outbound",
    status: "completed",
    outcome: "resolved",
    roleIds: ["operator"],
    dateLabel: "Today",
    startedAtLabel: "08:40",
    durationSeconds: 252,
    twilioSid: "CA1a2b3c4d5e6f708192a3b4c5d6e7f809",
    elevenConversationId: "elc_2a90ffb114",
    recordingAvailable: true,
    model: "grok-2",
    toolCalls: 2,
    summary:
      "Confirmed the vendor onboarding workflow completed and closed the open task.",
    transcript: [
      {
        id: "ch2-u1",
        speaker: "twin",
        text: "Calling to confirm the vendor onboarding workflow finished overnight.",
        timestamp: "00:03",
      },
      {
        id: "ch2-u2",
        speaker: "caller",
        text: "Yes, all three steps completed. You can close the task.",
        timestamp: "00:14",
      },
      {
        id: "ch2-u3",
        speaker: "twin",
        text: "Closed. I have logged it against the onboarding project.",
        timestamp: "00:21",
      },
    ],
    whispers: [],
  },
  {
    id: "ch-3",
    caller: "Unknown",
    fromNumber: "+1 (628) 555-0173",
    toNumber: "+1 (415) 555-0100",
    direction: "inbound",
    status: "missed",
    outcome: "voicemail",
    roleIds: ["public"],
    dateLabel: "Yesterday",
    startedAtLabel: "17:22",
    durationSeconds: 38,
    twilioSid: "CA55667788990011223344556677889900",
    elevenConversationId: "elc_0c1d2e3f45",
    recordingAvailable: true,
    model: "grok-2",
    toolCalls: 0,
    summary: "Caller left a voicemail asking for a media comment; no roles engaged.",
    transcript: [
      {
        id: "ch3-u1",
        speaker: "caller",
        text: "Hi, this is a reporter with the Chronicle — hoping to get a quick comment on the funding round. Please call me back.",
        timestamp: "00:06",
      },
    ],
    whispers: [],
  },
  {
    id: "ch-4",
    caller: "David Okafor",
    fromNumber: "+1 (415) 555-0100",
    toNumber: "+44 20 7946 0958",
    direction: "outbound",
    status: "completed",
    outcome: "info_provided",
    roleIds: ["financial", "private"],
    dateLabel: "Yesterday",
    startedAtLabel: "11:05",
    durationSeconds: 1267,
    twilioSid: "CAabcdef0123456789abcdef0123456789",
    elevenConversationId: "elc_9182736450",
    recordingAvailable: true,
    model: "grok-2",
    toolCalls: 5,
    summary:
      "Walked through personal account performance and tax-loss harvesting options; no action authorized.",
    transcript: [
      {
        id: "ch4-u1",
        speaker: "caller",
        text: "Where did we end the quarter on the personal account?",
        timestamp: "00:05",
      },
      {
        id: "ch4-u2",
        speaker: "twin",
        text: "Up 1.4% net. The drag was the small cash allocation we held into September.",
        timestamp: "00:15",
      },
      {
        id: "ch4-u3",
        speaker: "whisper",
        text: "Do not authorize any trades on this call.",
        timestamp: "00:33",
        whisperStatus: "spoken",
      },
      {
        id: "ch4-u4",
        speaker: "twin",
        text: "There are two tax-loss harvesting candidates. I can prepare them, but nothing will be executed without your sign-off.",
        timestamp: "00:44",
      },
      {
        id: "ch4-u5",
        speaker: "caller",
        text: "Prepare them and send for review.",
        timestamp: "00:58",
      },
    ],
    whispers: [
      {
        id: "ch4-w1",
        text: "Do not authorize any trades on this call.",
        queuedAt: "00:33",
        spokenAt: "00:44",
        usedInTraining: true,
      },
      {
        id: "ch4-w2",
        text: "Keep it to two candidates, not the full list.",
        queuedAt: "00:41",
        usedInTraining: false,
      },
    ],
  },
  {
    id: "ch-5",
    caller: "Priya Nair",
    fromNumber: "+1 (312) 555-0166",
    toNumber: "+1 (415) 555-0100",
    direction: "inbound",
    status: "completed",
    outcome: "escalated",
    roleIds: ["operator"],
    dateLabel: "Mar 3",
    startedAtLabel: "14:47",
    durationSeconds: 411,
    twilioSid: "CA0987654321fedcba0987654321fedcba",
    elevenConversationId: "elc_5647382910",
    recordingAvailable: true,
    model: "grok-2",
    toolCalls: 1,
    summary:
      "Reported a billing discrepancy outside the Twin's authority; escalated to the operator.",
    transcript: [
      {
        id: "ch5-u1",
        speaker: "caller",
        text: "We were double-charged on the March invoice.",
        timestamp: "00:07",
      },
      {
        id: "ch5-u2",
        speaker: "twin",
        text: "I can see the duplicate charge. Refunds above this amount need an operator, so I am flagging this now and someone will follow up within the hour.",
        timestamp: "00:20",
      },
    ],
    whispers: [],
  },
  {
    id: "ch-6",
    caller: "Outbound call",
    fromNumber: "+1 (415) 555-0100",
    toNumber: "+1 (917) 555-0110",
    direction: "outbound",
    status: "failed",
    outcome: "no_answer",
    roleIds: ["financial"],
    dateLabel: "Mar 3",
    startedAtLabel: "10:02",
    durationSeconds: 0,
    twilioSid: "CAfailed00000000000000000000000001",
    elevenConversationId: "elc_none000000",
    recordingAvailable: false,
    model: "grok-2",
    toolCalls: 0,
    summary: "No answer after three rings; no transcript.",
    transcript: [],
    whispers: [],
  },
  {
    id: "ch-7",
    caller: "James Reyes",
    fromNumber: "+1 (415) 555-0155",
    toNumber: "+1 (415) 555-0100",
    direction: "inbound",
    status: "completed",
    outcome: "dropped",
    roleIds: ["public", "financial"],
    dateLabel: "Mar 2",
    startedAtLabel: "16:19",
    durationSeconds: 96,
    twilioSid: "CAdropped1122334455667788990011223",
    elevenConversationId: "elc_1029384756",
    recordingAvailable: true,
    model: "grok-2",
    toolCalls: 1,
    summary: "Call dropped mid-answer due to a network issue on the caller side.",
    transcript: [
      {
        id: "ch7-u1",
        speaker: "caller",
        text: "Quick one — are we commenting publicly on the raise?",
        timestamp: "00:05",
      },
      {
        id: "ch7-u2",
        speaker: "twin",
        text: "We are keeping public comments to the approved statement. I can send you the language —",
        timestamp: "00:14",
        partial: true,
      },
    ],
    whispers: [],
  },
];

export function getHistoryCall(id: string): CallHistoryEntry | undefined {
  return callHistory.find((call) => call.id === id);
}
